name: CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 1
    - name: Download and extract test data 
      env:
          GITHUB_WORKSPACE: ${{github.workspace}}
      run: |
        sh downloadTestData.sh
    - uses: agahkarakuzu/moxunit-action@master
      with:
        src: src
        data: Test/testData
        pkg: image io
        with_coverage: true
        cover_xml_file: coverage.xml
    - uses: actions/upload-artifact@v1
      with:
        name: coverage_file
        path: coverage.xml
    - uses: codecov/codecov-action@v1
      with:
       token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
       file:  coverage.xml # optional
       flags: unittests # optional
       name: codecov-umbrella # optional
       fail_ci_if_error: true # optional (default = false)
